Remove parameter name usage for AutowireDatabase
mongodb-labs/symfony-mongodb pull request #13
Opened 2023-12-08 14:41 UTC by alcaeus

As it is, there is no way to autowire the default database without explicitly specifying the name, instead it will always use the parameter name. To work around this, we remove usage of the parameter name and fall back to the default database; not specifying a `default_database` option or the `database` parameter in the `AutowireDatabase` attribute will result in an exception. We could use some magic to fall back to the parameter name if no default database was set, but I don't believe that results an improvement and only makes for more confusing rules.

2023-12-08 14:43 UTC, OskarStark requested changes
Please adjust the README examples

2023-12-09 08:34 UTC, GromNaN reviewed
I don't get the issue.

2023-12-09 08:34 UTC, GromNaN commented on tests/Unit/Attribute/AutowireDatabaseTest.php
> +        $this->assertSame('%MongoDB\Client.default_database%', $definition->getArgument(0));
That's an ugly parameter name. Can we find something more conventional?

2023-12-09 08:45 UTC, OskarStark approved these changes

2023-12-09 08:49 UTC, alcaeus commented
> I don't get the issue.

Before this PR, there was no way to inject a `Database` instance for the default database without specifying the database name. Since the database name may change between environments (as it did in my case), this is not a very good option.

2023-12-09 08:50 UTC, alcaeus commented on tests/Unit/Attribute/AutowireDatabaseTest.php
> +        $this->assertSame('%MongoDB\Client.default_database%', $definition->getArgument(0));
> That's an ugly parameter name. Can we find something more conventional?

I'll address that in a separate PR - maybe we can always use `<clientId>.default_database`

2023-12-09 11:46 UTC, GromNaN approved these changes

2023-12-09 11:51 UTC, merged